import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { CircleMarker, MapContainer, Polyline, TileLayer, Tooltip, useMap } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import './styles.css';

const demo = [{airline:'IndiGo',code:'6E 236',dep:'06:10',arr:'08:20',duration:'2h 10m',price:5240},{airline:'Air India',code:'AI 864',dep:'09:35',arr:'11:55',duration:'2h 20m',price:5680},{airline:'Akasa Air',code:'QP 1324',dep:'14:40',arr:'17:05',duration:'2h 25m',price:5950},{airline:'SpiceJet',code:'SG 328',dep:'19:20',arr:'21:35',duration:'2h 15m',price:6140}];
const money = new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0});
const iata = v => (v.match(/\(([A-Za-z]{3})\)/)?.[1] || v.slice(0,3)).toUpperCase();
const api = async path => { const r=await fetch(path); if(!r.ok) throw Error(); return r.json(); };
function Nav({page,go}) { return <nav><button className="brand" onClick={()=>go('home')}>✈ AP<span>ix</span></button><div className="navlinks"><button onClick={()=>go('home')}>Home</button><button className={page==='dashboard'?'active':''} onClick={()=>go('dashboard')}>Dashboard</button><button className={page==='map'?'active':''} onClick={()=>go('map')}>Route explorer</button></div><button className="sign" onClick={()=>go('login')}>Sign in</button></nav> }
function Home({go}) { return <><Nav go={go}/><section className="hero"><div><b className="eyebrow">REAL-TIME AIRFARE INTELLIGENCE</b><h1>Find smarter ways to <em>fly.</em></h1><p>Compare fares, understand route demand and discover the right time to book your next domestic flight.</p><button className="primary" onClick={()=>go('map')}>Explore routes →</button> <button className="secondary" onClick={()=>go('dashboard')}>View dashboard</button></div><div className="routehero"><h2>Today’s popular route</h2><p>Live fares from connected airline partners</p><div className="routecodes"><b>DEL<small>New Delhi</small></b><span>✈</span><b>BOM<small>Mumbai</small></b></div><div className="fare">from <strong>₹5,240</strong><mark>↓ 12%</mark></div></div></section><div className="stats">{[['32','Routes monitored'],['15','Cities covered'],['5','Data partners'],['30 sec','Live refresh']].map(x=><div><b>{x[0]}</b><small>{x[1]}</small></div>)}</div></> }
function Field({label,value,set}) {return <label className="field"><small>{label}</small><input value={value} onChange={e=>set(e.target.value)}/></label>}
function MapViewport({points}) {const map=useMap();useEffect(()=>{if(points?.length===2)map.fitBounds(points,{padding:[45,45],maxZoom:6})},[map,points]);return null}
function Map({from,to,points}) {const route=points?.length===2?points:[[28.6139,77.209],[19.076,72.8777]];return <MapContainer className="realmap" center={[22.7,79]} zoom={5} scrollWheelZoom><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><Polyline positions={route} pathOptions={{color:'#1769ff',weight:4,dashArray:'8 8'}}/><CircleMarker center={route[0]} radius={9} pathOptions={{color:'#1769ff',fillColor:'#1769ff',fillOpacity:1}}><Tooltip permanent>{from}</Tooltip></CircleMarker><CircleMarker center={route[1]} radius={9} pathOptions={{color:'#f2773c',fillColor:'#f2773c',fillOpacity:1}}><Tooltip permanent>{to}</Tooltip></CircleMarker><MapViewport points={route}/></MapContainer>}
function Flight({f,from,to}) {return <article className="flight"><div><b>{f.airline} <small>{f.code}</small></b><i>{f.source||'Demo data'}</i></div><strong>{money.format(f.price)}</strong><div className="times"><b>{f.dep}<small>{from}</small></b><span>{f.duration}<small>Non-stop</small></span><b>{f.arr}<small>{to}</small></b></div><button>View provider offer →</button></article>}
function Explorer({go}) {const [origin,setOrigin]=useState('Delhi (DEL)'),[dest,setDest]=useState('Mumbai (BOM)'),[codes,setCodes]=useState({from:'DEL',to:'BOM'}),[flights,setFlights]=useState(demo),[points,setPoints]=useState([[28.6139,77.209],[19.076,72.8777]]),[message,setMessage]=useState('Map is showing Delhi to Mumbai');const from=codes.from,to=codes.to;async function search(){setMessage('Finding the correct airports…');try{const places=await api(`/api/places?origin=${encodeURIComponent(origin)}&destination=${encodeURIComponent(dest)}`);setPoints(places.points);const resolvedFrom=places.origin.code,resolvedTo=places.destination.code;if(!resolvedFrom||!resolvedTo){setMessage(`Map route found, but select a recognised airport for fares.`);setFlights(demo);return}setCodes({from:resolvedFrom,to:resolvedTo});setMessage(`Map route: ${places.origin.name} → ${places.destination.name}`);try{const fares=await api(`/api/flights/search?origin=${resolvedFrom}&destination=${resolvedTo}`);setFlights(fares.flights)}catch{setFlights(demo)}}catch{setMessage('Could not find those cities. Try a city name or a three-letter airport code.')}}return <><Nav page="map" go={go}/><main><b className="eyebrow">LIVE ROUTE INTELLIGENCE</b><h1>Explore your flight route</h1><p className="muted">Enter city names such as Chennai or Mumbai — airport codes are detected automatically.</p><section className="search"><Field label="FROM" value={origin} set={setOrigin}/><button className="swap" onClick={()=>{setOrigin(dest);setDest(origin)}}>⇄</button><Field label="TO" value={dest} set={setDest}/><button className="primary" onClick={search}>Search flights</button></section><p className="live"><i/> {message}</p><div className="routegrid"><section className="mappanel"><h2>{origin.replace(/\s*\(.*/,'')} → {dest.replace(/\s*\(.*/,'')}</h2><p>OpenStreetMap route visualisation</p><Map from={from} to={to} points={points}/></section><section className="results"><h2>Available flights <small>{flights.length} options</small></h2>{flights.map((f,n)=><Flight key={n} f={f} from={from} to={to}/>)}</section></div></main></>}
function Dashboard({go}) {const [data,setData]=useState();const [error,setError]=useState('');useEffect(()=>{let live=true;const load=()=>api('/api/dashboard').then(d=>live&&setData(d)).catch(()=>live&&setError('API server offline — showing preview data.'));load();const id=setInterval(load,30000);return()=>{live=false;clearInterval(id)}},[]);const routes=data?.routes||demo.map((f,n)=>({route:['DEL → BOM','DEL → BLR','BOM → DEL','MAA → DEL'][n],lowest:f.price,change:[-12,4,8,-3][n]}));return <><Nav page="dashboard" go={go}/><main className="dash"><header><div><b className="eyebrow">FARE MONITOR</b><h1>Good morning, traveller 👋</h1><p>Real-time domestic airfare movement.</p></div><p className="live"><i/> {data?`Live · ${new Date(data.updatedAt).toLocaleTimeString()}`:'Connecting…'}</p></header>{error&&<div className="notice">{error}</div>}<div className="metrics">{[['▣','Lowest fare today',money.format(Math.min(...routes.map(r=>r.lowest)))],['↗','Routes monitored','32'],['◉','Provider sources',data?.sources?.length||1],['⌁','Refresh interval','30 sec']].map(x=><article><span>{x[0]}</span><small>{x[1]}</small><b>{x[2]}</b><em>Live data</em></article>)}</div><div className="dashgrid"><section className="chartcard"><h2>Airfare price index</h2><p>Last 30 days · DEL to BOM</p><div className="chart"><svg viewBox="0 0 600 180"><path d="M0 135 L75 120 L140 126 L200 91 L250 105 L300 80 L360 110 L420 85 L480 90 L550 42 L600 65"/></svg></div></section><section className="movements"><h2>Top fare movements</h2>{routes.map(r=><div><span><b>{r.route}</b><small>Lowest available fare</small></span><span><b>{money.format(r.lowest)}</b><small className={r.change>0?'up':'down'}>{r.change>0?'▲':'▼'} {Math.abs(r.change)}%</small></span></div>)}</section></div></main></>}
function Login({go}) {return <section className="login"><aside><b className="brand">✈ AP<span>ix</span></b><h1>Travel decisions, made clearer.</h1><p>Monitor flight fares, build routes, and get notified when prices move.</p></aside><form onSubmit={e=>{e.preventDefault();go('dashboard')}}><b className="eyebrow">WELCOME BACK</b><h1>Sign in to APix</h1><p>Enter your details to continue to your dashboard.</p><label>Email address<input type="email" placeholder="you@example.com"/></label><label>Password<input type="password" placeholder="••••••••"/></label><button className="primary">Sign in</button><small>Demo sign-in — authentication can be connected later.</small></form></section>}
function App(){const [page,setPage]=useState(location.hash.slice(1)||'home');useEffect(()=>{const f=()=>setPage(location.hash.slice(1)||'home');addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);const go=x=>location.hash=x;return page==='map'?<Explorer go={go}/>:page==='dashboard'?<Dashboard go={go}/>:page==='login'?<Login go={go}/>:<Home go={go}/>};createRoot(document.getElementById('app')).render(<App/>);
